### ISSUE TITLE
void-variable magit-buffer-lock-functions prevents interface popup

### ISSUE THREAD

**Issue by weatherman2095** [vermiculus/magithub#300]
Up-to-date Melpa installation seems to still have this issue which prevents the menu popup. #171 refers to it as well, though I do not know if the cause is the same.

I'm using the use-package fix mentionned in #299 to fix that issue as well.

```elisp
Debugger entered--Lisp error: (void-variable magit-buffer-lock-functions)
  byte-code("\301\302BB\301\207" [magit-buffer-lock-functions magithub-issue-view-mode magithub-issue-view--lock-value] 2)
  require(magithub-issue-view)
  eval-buffer(#<buffer  *load*-235220> nil "/home/user/.emacs.d/elpa/magithub-20180307.446/magithub-notification.el" nil t)  ; Reading at buffer position 950
  load-with-code-conversion("/home/user/.emacs.d/elpa/magithub-20180307.446/magithub-notification.el" "/home/user/.emacs.d/elpa/magithub-20180307.446/magithub-notification.el" nil t)
  require(magithub-notification)
  eval-buffer(#<buffer  *load*-511660> nil "/home/user/.emacs.d/elpa/magithub-20180307.446/magithub-dash.el" nil t)  ; Reading at buffer position 993
  load-with-code-conversion("/home/user/.emacs.d/elpa/magithub-20180307.446/magithub-dash.el" "/home/user/.emacs.d/elpa/magithub-20180307.446/magithub-dash.el" nil t)
  require(magithub-dash)
  eval-buffer(#<buffer  *load*> nil "/home/user/.emacs.d/elpa/magithub-20180307.446/magithub.el" nil t)  ; Reading at buffer position 2033
  load-with-code-conversion("/home/user/.emacs.d/elpa/magithub-20180307.446/magithub.el" "/home/user/.emacs.d/elpa/magithub-20180307.446/magithub.el" nil t)
  autoload-do-load((autoload "magithub" nil t nil) magithub-dispatch-popup)
  command-execute(magithub-dispatch-popup)

```

**Comment by vermiculus** [comment]
Make sure you're using the most recent version of Magit; I don't believe this variable is in stable yet.

**Comment by weatherman2095** [comment]
I checked and my Melpa source is https://melpa.org/packages/, so normally it should be working.

**Comment by weatherman2095** [comment]
That was indeed the issue. Thanks.

**Comment by aspiers** [comment]
I don't understand this resolution.  I still see this problem and I have both the latest `magit` and `magithub` from MELPA:

```
  magit              20180519.1008 installed             A Git porcelain inside Emacs.
  magithub           20180519.1216 installed             Magit interfaces for GitHub
```

Please can someone explain what I'm missing?

**Comment by vermiculus** [comment]
With `magit-buffer-lock-functions` specifically?

https://github.com/magit/magit/blob/9f838cc041db2ccfe0d67a501e3188a8a61e4446/lisp/magit-mode.el#L861-L882

**Comment by aspiers** [comment]
Yes specifically.

**Comment by aspiers** [comment]
Wow, the problem magically vanished just now.  I hate heisenbugs :-(  Only thing I can think of is that I just nuked my whole `~/.emacs.d/el-get`, so it's conceivable that there was an ancient `magit-mode` in there.  But I don't think there was.
